name: CI with Keploy API Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-api:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: --health-cmd "mongo --eval 'db.runCommand({ connectionStatus: 1 })'" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Start Your App in Background
        run: |
          nohup node app.js &
          sleep 10  # give app time to boot

      - name: Install Keploy CLI
        run: |
          curl --silent -L https://keploy.io/ent/install.sh | bash

      - name: Run Keploy Test Suite
        run: |
        export KEPLOY_API_KEY=pt1uGJzA8CCOMIs5Yw== && keploy test-suite --app=b9d7276a-8381-47c5-978c-696b3d15b7f8 --base-path http://localhost:3000/user/create --cloud
